### ISSUE TITLE
How to configure the home page path?

### ISSUE THREAD

**Issue by yakou32** [Marktawa/strapi-nuxt-preview#1]
Thank you so much for this example.

Following it, I have now created two pages that work perfectly:
- /en (using english data)
- /fr (using french data)

However, the root path is still available ("/") - this one is not created by createPage, and stands for the layout which consumes data.

As a result, this root page is empty.

How can I fix this?

I tried two options, assuming fr is the default locale:
- to create two pages (`/en` for English and `/` for French) -> this one doesn't work
- to redirect `/` to  `/fr` -> I got stuck with gatsby-plugin-i18n that doesn't use the same logic (although taking account the browser's locale as a default would be great)

What would you advise?

**Comment by Marktawa** [comment]
Hi @yakou32 
I'm glad to hear you found the tutorial helpful.
Please raise your issue on this [link](https://github.com/Marktawa/tags-strapi-bluedolphin/issues). 
I entered the wrong link in my README.

Sorry for the inconvenience.
